project:
  type: website
  output-dir: docs

website:
  title: "PruebaRstudio"
  description: ""
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Ver código"
    lang: es
    css: styles.css